import { defineRailway, github, preserve, project, service } from "railway/iac";

export default defineRailway(() => {
  const vibedigestSource = github("Neallin-917/VibeDigest");

  const api = service("VibeDigest", {
    source: vibedigestSource,
    build: {
      builder: "DOCKERFILE",
      dockerfilePath: "backend/Dockerfile",
      watchPatterns: [
        "/backend/**",
        "/config/**",
        "/pyproject.toml",
        "/uv.lock",
        "/.railway/**",
      ],
    },
    deploy: {
      startCommand: "/bin/sh -c 'uvicorn main:app --host 0.0.0.0 --port $PORT'",
      healthcheckPath: "/health/ready",
      healthcheckTimeout: 100,
    },
    replicas: { "us-west2": 1 },
    domains: ["api.vibedigest.io"],
    networking: { privateNetworkEndpoint: "vibedigest" },
    env: {
      ALLOWED_ORIGINS: preserve(),
      BACKEND_CONTAINER_PORT: preserve(),
      BACKEND_PORT: preserve(),
      COGNITION_DELAY: preserve(),
      COGNITION_SEQUENTIAL: preserve(),
      COMPOSE_PROJECT_NAME: preserve(),
      CREEM_API_BASE: preserve(),
      CREEM_API_KEY: preserve(),
      CREEM_WEBHOOK_SECRET: preserve(),
      DATABASE_URL: preserve(),
      DB_PORT: preserve(),
      DEV_AUTH_BYPASS: preserve(),
      FEEDBACK_FROM_EMAIL: preserve(),
      FEEDBACK_TO_EMAIL: preserve(),
      FRONTEND_PORT: preserve(),
      FRONTEND_URL: preserve(),
      LANGCHAIN_API_KEY: preserve(),
      LANGCHAIN_ENDPOINT: preserve(),
      LANGCHAIN_PROJECT: preserve(),
      LANGCHAIN_TRACING_V2: preserve(),
      LANGFUSE_BASE_URL: preserve(),
      LANGFUSE_PUBLIC_KEY: preserve(),
      LANGFUSE_SECRET_KEY: preserve(),
      LANGGRAPH_CONTAINER_PORT: preserve(),
      LANGGRAPH_PORT: preserve(),
      LANGSMITH_API_KEY: preserve(),
      LANGSMITH_ENDPOINT: preserve(),
      LANGSMITH_PROJECT: preserve(),
      LANGSMITH_TRACING: preserve(),
      LLM_PROVIDER: preserve(),
      LLM_RUNTIME: preserve(),
      LOG_BACKTRACE: preserve(),
      LOG_DIAGNOSE: preserve(),
      LOG_FILE: preserve(),
      LOG_FILE_COMPRESSION: preserve(),
      LOG_FILE_RETENTION: preserve(),
      LOG_FILE_ROTATION: preserve(),
      LOG_JSON: preserve(),
      LOG_LEVEL: preserve(),
      MOCK_MODE: preserve(),
      NEXT_PUBLIC_SENTRY_DSN: preserve(),
      OPENAI_SUMMARY_MATCH_THRESHOLD: preserve(),
      OPENROUTER_API_KEY: preserve(),
      PODCAST_TASK_QUEUE_NAME: preserve(),
      PROJECT_NAME: preserve(),
      REDIS_PORT: preserve(),
      RESEND_API_KEY: preserve(),
      SENTRY_DSN: preserve(),
      SENTRY_ENVIRONMENT: preserve(),
      SUMMARY_STRATEGY: preserve(),
      SUPABASE_JWT_SECRET: preserve(),
      SUPABASE_SERVICE_KEY: preserve(),
      SUPABASE_URL: preserve(),
      SUPADATA_API_KEY: preserve(),
      VIBEDIGEST_DEMO_USER_ID: preserve(),
    },
  });
  const hostedWorker = service("VibeDigest-Worker", {
    source: vibedigestSource,
    build: {
      buildEnvironment: "V3",
      builder: "DOCKERFILE",
      dockerfilePath: "backend/Dockerfile",
      watchPatterns: [
        "/backend/**",
        "/config/**",
        "/pyproject.toml",
        "/uv.lock",
        "/.railway/**",
      ],
    },
    deploy: {
      startCommand: "python worker.py",
    },
    replicas: { "us-west2": 1 },
    networking: { privateNetworkEndpoint: "vibedigest-worker" },
    env: {
      COGNITION_DELAY: preserve(),
      COGNITION_SEQUENTIAL: preserve(),
      DATABASE_URL: preserve(),
      FRONTEND_URL: preserve(),
      LANGCHAIN_API_KEY: preserve(),
      LANGCHAIN_ENDPOINT: preserve(),
      LANGCHAIN_PROJECT: preserve(),
      LANGCHAIN_TRACING_V2: preserve(),
      LANGFUSE_BASE_URL: preserve(),
      LANGFUSE_PUBLIC_KEY: preserve(),
      LANGFUSE_SECRET_KEY: preserve(),
      LANGSMITH_API_KEY: preserve(),
      LANGSMITH_ENDPOINT: preserve(),
      LANGSMITH_PROJECT: preserve(),
      LANGSMITH_TRACING: preserve(),
      LLM_PROVIDER: preserve(),
      LLM_RUNTIME: preserve(),
      LOG_JSON: preserve(),
      LOG_LEVEL: preserve(),
      MOCK_MODE: preserve(),
      OPENAI_SUMMARY_MATCH_THRESHOLD: preserve(),
      OPENROUTER_API_KEY: preserve(),
      SENTRY_DSN: preserve(),
      SENTRY_ENVIRONMENT: preserve(),
      SUMMARY_STRATEGY: preserve(),
      SUPABASE_JWT_SECRET: preserve(),
      SUPABASE_SERVICE_KEY: preserve(),
      SUPABASE_URL: preserve(),
      SUPADATA_API_KEY: preserve(),
      TASK_QUEUE_EXECUTION_TIMEOUT_SECONDS: preserve(),
      TASK_QUEUE_HEARTBEAT_INTERVAL_SECONDS: preserve(),
      TASK_QUEUE_MAX_ATTEMPTS: preserve(),
      TASK_QUEUE_MAX_POLL_SECONDS: preserve(),
      TASK_QUEUE_NAME: preserve(),
      TASK_QUEUE_VISIBILITY_TIMEOUT_SECONDS: preserve(),
      WORKER_PROFILE: preserve(),
    },
  });

  const podcastDiscovery = service("VibeDigest-Podcast-Discovery", {
    source: vibedigestSource,
    build: {
      buildEnvironment: "V3",
      builder: "DOCKERFILE",
      dockerfilePath: "backend/Dockerfile",
      watchPatterns: [
        "/backend/**",
        "/config/podcast-sources.json",
        "/pyproject.toml",
        "/uv.lock",
        "/.railway/**",
      ],
    },
    deploy: {
      startCommand: "python scripts/podcasts/discover.py --since-days 7 --max-enqueues 4",
      cronSchedule: "0 */6 * * *",
      restartPolicyType: "NEVER",
    },
    networking: { privateNetworkEndpoint: "vibedigest-podcast-discovery" },
    env: {
      DATABASE_URL: api.env.DATABASE_URL,
      DEV_AUTH_BYPASS: "false",
      EVENTLET_NO_GREENDNS: "yes",
      LLM_RUNTIME: "api",
      LOG_JSON: api.env.LOG_JSON,
      LOG_LEVEL: api.env.LOG_LEVEL,
      MOCK_MODE: "false",
      PODCAST_TASK_QUEUE_NAME: api.env.PODCAST_TASK_QUEUE_NAME,
      SUPABASE_JWT_SECRET: api.env.SUPABASE_JWT_SECRET,
      SUPABASE_SERVICE_KEY: api.env.SUPABASE_SERVICE_KEY,
      SUPABASE_URL: api.env.SUPABASE_URL,
      VIBEDIGEST_DEMO_USER_ID: api.env.VIBEDIGEST_DEMO_USER_ID,
    },
  });

  return project("steadfast-vibrancy", {
    resources: [api, hostedWorker, podcastDiscovery],
  });
});
